meta-mchp-common: recipes-kernel: add cpupower-systemd optional package
cpupower ship a systemd service and config file in kernel source tree
since kernel 6.16. Package them as a separate package cpupower-systemd
to be installed if wanted. DO this in a bbappend temporarily until this
is fixed in meta-openembedded. This fixes the following QA issue:

ERROR: cpupower-1.0-r0 do_package: QA Issue: cpupower: Files/directories
were installed but not shipped in any package:
  /usr/lib/systemd
  /usr/lib/systemd/system
  /usr/lib/systemd/system/cpupower.service

Signed-off-by: Valentina Fernandez <valentina.fernandezalanis@microchip.com>